### ISSUE TITLE
Kill all enemies then end wave problem

### ISSUE THREAD

**Issue by ShinyLuxray** [ShinyLuxray/LastStandDefence#12]
KH your gui stops the program at line 706 in LSD.java
you'd probably want to add to the fire() method where it says waveDone = true
We get Outtabounds exception because the GUI tries to draw the enemy even after it is removed.
Please fix or suggest something we can do to fix it. Thanks!

**Comment by thunderbird2678** [comment]
Fixed as of this morning.
