### ISSUE TITLE
Enemy Class

### ISSUE THREAD

**Issue by thunderbird2678** [ShinyLuxray/LastStandDefence#5]
Is there going to be a data field called "ID" that can set the type of enemy? Or does my GameBoard class just choose a random image out of the assortment of enemy images to draw at any given time?

Also, just sayin', but a constructor for the class would be nice, y'know..?

**Comment by Evanli1999** [comment]
Was thinking that for simplicity, we make all units move at the same rate. So in that case, the only thing the "ID" would effect is the image of the unit. (I guess we could, but what's the point?")

On another note, we could also incorporate a damage adjuster according to round number, so towers gradually do less damage to units (effect of buffing units as the round progresses)

**Comment by ShinyLuxray** [comment]
I believe making all our enemies move at the same rate will make the game inflexible to changes when we want to make them more advanced. I am fine with all units of one type (id) moving at the same rate.

**Comment by thunderbird2678** [comment]
@Evanli1999 the damage adjuster seems very reasonable; which class should that be placed in? Are we adjusting the turrets' damage or the enemies' health? Probably the latter, right, in which case, I suppose you'd need to initialize in LSD the waves of enemies with progressively increasing HP.

@ShinyLuxray do we really have time to make it much more advanced than that, though? I mean, to be fair, look at even Onslaught 2; they have a constant enemy movement rate. I think making those variable would overcomplicate things.

**Comment by ShinyLuxray** [comment]
Well, it depends if you can layer enemy images over each other, and remove one in between at will.
If you can, then I'll make a rate field for enemy, which will start a thread, that continues until the enemy dies or reaches the end.
Either way, I'll work on an initializer for the Enemy class tonight.
