### ISSUE TITLE
Unifying drawnEnemy and actual enemies

### ISSUE THREAD

**Issue by ShinyLuxray** [ShinyLuxray/LastStandDefence#7]
In the current set up, the enemies aren't moving at all. Only pictures.
Remap the draw Enemy arraylist to LSD.wave
Please close this issue when it has been resolved.

**Comment by thunderbird2678** [comment]
Should I then write a setPos method in the Enemy class and have the gameboard set the enemy's position every time an enemy is moved?

**Comment by thunderbird2678** [comment]
Done.
